// src/components/Navbar.jsx
import React from 'react'
import { NavLink } from "react-router-dom";
import { ExternalLink } from "../helpers/common";


const Navbar = () => {
  return (
    <div className="flex font-montserrat font-medium">
      <div className="flex sm:hidden w-full justify-center items-center text-center h-16 bg-gray-100 border-b-2 border-gray-300">
        <NavLink exact to="/" className="block w-20 h-8 m-auto"><img src="/logo.png" alt="logo" /></NavLink>
      </div>
      <div className="hidden sm:flex flex-row w-screen bg-gray-100 sm:p-4 justify-between z-10 border-b-2  border-gray-300">
        <NavLink exact to="/" className="ml-10 w-20 h-8 "><img src="/logo.png" alt="logo"></img></NavLink>
        <div className="justify-flex-end mt-1 mr-10">
          <NavLink exact to="/explore" className="ml-10 hover:text-blue-800" activeClassName="text-blue-600">Explore</NavLink>
          <NavLink exact to="/query" className="ml-10 hover:text-blue-800" activeClassName="text-blue-600">Query</NavLink>
          <NavLink exact to="/about" className="ml-10 hover:text-blue-800" activeClassName="text-blue-600">About</NavLink>
          <NavLink exact to="/team" className="ml-10 hover:text-blue-800" activeClassName="text-blue-600">Team</NavLink>
          <ExternalLink href="https://github.com/ababaian/serratus" className="ml-8 bg-white font-mono font-normal border-2 border-gray-600 rounded-lg p-2 hover:text-blue-600 hover:border-blue-600">GitHub</ExternalLink>
        </div>
      </div>
    </div>
  )
}

export default Navbar;

// src/components/Navbar.vue
<template>          
  <header class="text-gray-700 body-font top-0 fixed w-full bg-white shadow-lg">
    <div class="container mx-auto flex flex-wrap p-2 flex-col md:flex-row items-center">
      <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">

        <img src="@/assets/images/logo.png" v-scroll-to="'#home'" class="w-24 h-12 cursor-pointer"/>
        <!-- <span class="ml-3 text-xl">Serratus</span> -->
      </a>
      <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
      <!-- <router-link class="mr-16 hover:text-gray-900" to="/">Home</router-link> -->
      <div v-scroll-to="'#home'" class="mr-16 text-black hover:text-gray-900 cursor-pointer" >Home</div>
      <div v-scroll-to="'#about'" class="mr-16 text-black hover:text-gray-900 cursor-pointer" >About</div>
      <!-- <div v-scroll-to="'#info'" class="mr-16  text-black hover:text-gray-900 cursor-pointer" >Info</div> -->
      <a onClick="window.open(this.href); return false" href="https://github.com/ababaian/serratus" class=" text-black hover:text-gray-900 cursor-pointer" ><div   >Github</div></a>
      </nav>

    </div>
  </header>
</template>

<script>
export default {
  name: 'Navbar',
  props: {
    msg: String
  }
}
</script>

<style scoped>
logo {
  filter: invert(100%)
}

</style>
