// src/components/Navbar.vue
<template>          
  <header class="text-gray-700 body-font top-0 fixed w-full bg-white shadow-lg">
    <div class="container mx-auto flex flex-wrap p-2 flex-col md:flex-row items-center">
      <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">

        <img src="@/assets/images/logo.png" v-scroll-to="'#home'" class="w-24 h-12 cursor-pointer"/>
        <!-- <span class="ml-3 text-xl">Serratus</span> -->
      </a>
      <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
      <!-- <router-link class="mr-16 hover:text-gray-900" to="/">Home</router-link> -->
      <div v-scroll-to="'#home'" class="mr-16 text-black hover:text-gray-900 cursor-pointer" >Home</div>
      <div v-scroll-to="'#about'" class="mr-16 text-black hover:text-gray-900 cursor-pointer" >About</div>
      <!-- <div v-scroll-to="'#info'" class="mr-16  text-black hover:text-gray-900 cursor-pointer" >Info</div> -->
      <a onClick="window.open(this.href); return false" href="https://github.com/ababaian/serratus" class=" text-black hover:text-gray-900 cursor-pointer" ><div   >Github</div></a>
      </nav>

    </div>
  </header>
</template>

<script>
export default {
  name: 'Navbar',
  props: {
    msg: String
  }
}
</script>

<style scoped>
logo {
  filter: invert(100%)
}

</style>

// src/components/Navbar.tsx
import React from 'react'
import { NavLink } from 'react-router-dom'
import { ExternalLink } from 'common'
import { routes } from 'common/routes'

export const Navbar = () => {
    return (
        <div className='flex font-montserrat font-medium'>
            <div className='flex sm:hidden w-full justify-center items-center text-center h-16 bg-gray-50 border-b-2 border-gray-200'>
                <NavLink exact to={routes.home.path} className='block w-20 h-8 m-auto'>
                    <img src='/logo.png' alt='logo' />
                </NavLink>
            </div>
            <div className='hidden sm:flex flex-row w-screen bg-gray-50 sm:p-4 justify-between z-10 border-b-2  border-gray-200'>
                <NavLink exact to={routes.home.path} className='ml-10 w-20 h-8 '>
                    <img src='/logo.png' alt='logo'></img>
                </NavLink>
                <div className='justify-flex-end mt-1 mr-10'>
                    <NavLink
                        exact
                        to={routes.nucleotideExplorer.path}
                        className='ml-10 hover:text-blue-800'
                        activeClassName='text-blue-600'>
                        Explorer (NT)
                    </NavLink>
                    <NavLink
                        exact
                        to={routes.rdrpExplorer.path}
                        className='ml-10 hover:text-blue-800'
                        activeClassName='text-blue-600'>
                        Explorer (RdRP)
                    </NavLink>
                    <NavLink
                        exact
                        to={routes.palmid.path}
                        className='ml-10 hover:text-blue-800'
                        activeClassName='text-blue-600'>
                        palmID (beta)
                    </NavLink>
                    <NavLink
                        exact
                        to={routes.geo.path}
                        className='ml-10 hover:text-blue-800'
                        activeClassName='text-blue-600'>
                        Map (beta)
                    </NavLink>
                    <NavLink
                        exact
                        to={routes.trees.path}
                        className='ml-10 hover:text-blue-800'
                        activeClassName='text-blue-600'>
                        Trees (beta)
                    </NavLink>
                    <NavLink
                        exact
                        to={routes.about.path}
                        className='ml-10 hover:text-blue-800'
                        activeClassName='text-blue-600'>
                        About
                    </NavLink>
                    <NavLink
                        exact
                        to={routes.team.path}
                        className='ml-10 hover:text-blue-800'
                        activeClassName='text-blue-600'>
                        Team
                    </NavLink>
                    <ExternalLink
                        href='https://www.biorxiv.org/content/10.1101/2020.08.07.241729v2'
                        className='ml-6 bg-white font-mono font-normal border-2 border-gray-600 rounded-lg p-2 hover:text-blue-600 hover:border-blue-600'>
                        Preprint
                    </ExternalLink>
                    <ExternalLink
                        href='https://github.com/ababaian/serratus/wiki'
                        className='ml-6 bg-white font-mono font-normal border-2 border-gray-600 rounded-lg p-2 hover:text-blue-600 hover:border-blue-600'>
                        Wiki
                    </ExternalLink>
                </div>
            </div>
        </div>
    )
}
